### ISSUE TITLE
Board Deletion Bug

### ISSUE THREAD

**Issue by Walaryne** [vichan-devel/vichan#331] opened 2019-03-25 12:46 UTC
Hi there,
When I delete a board, and return to my dashboard, all other boards disappear, and I can no longer edit them, all I'm left with is a "Create Board" button.
Manually readding the board allows me to access it once more, everything intact, since it doesn't actually delete any more than the board I specified.

Also, I'm using PHP 7.3.3 with memcached.

**Comment by ctrlcctrlv** [comment] 2019-03-26 01:54
This is a possible 7.3 regression. Try deleting a board under PHP5, also turn on logging since it sounds like an error is being omitted.

**Comment by fallenPineapple** [comment] 2019-05-29 21:08
@ctrlcctrlv 
May be of relevance, under PHP 7.2 when deleting any board I get the error **Truncated incorrect DOUBLE value: 'b'** if there is a board in the list above /b/ it will throw the same error except with the uri of that board instead. Under PHP 7.0 it seems to function as intended.

**Comment by ctrlcctrlv** [comment] 2019-09-22 08:57
Fixed by https://github.com/vichan-devel/vichan/commit/e15e966cdbda7b658af27b1a498606a82e8f8c5e

**Closed by ctrlcctrlv** 2019-09-22 08:57 UTC
Labels: more info needed, php72-regression

**Comment by z0z0z** [comment] 2019-11-09 15:51
I also had this happen to me.

Just creating the boards again resolved the issue and all data was intact, however for me I had the `posts_foo` tables damaged.

If you tried to select "recent posts" in the dashboard, or search in the dashboard, you'd get a message saying it crashed and needs to be repaired.

To my surprise, simply just logging into the MySQL database, and doing `repair table posts_foo` just worked.
