### ISSUE TITLE
File upload: Operation not permitted

### ISSUE THREAD

**Issue by pfeifferj** [vichan-devel/vichan#334] opened 2019-04-17 17:57 UTC
I'm getting this error when sending a post with an image attached:
`rename(/tmp/converts05r8X,b/thumb/1555523148268.png): Operation not permitted`

All dependencies are installed and verified.

I also ran
`chmod -F 777 tmp`
so directory permission shouldn't be an issue.

Additionally, I tried disabling rename altogether with
```
$config['additional_javascript'][] = 'js/jquery.min.js';
$config['additional_javascript'][] = 'js/download-original.js';
```
as described [here](https://github.com/vichan-devel/vichan/issues/244)

The same error still presists, though.

**Comment by ctrlcctrlv** [comment] 2019-04-18 12:33
Hi. Disabling renaming doesn't actually disable renaming (confusing, I know), just while it's doing the actual Unix `rename` function, instead of writing to something like `1555523148268.png`, it will write to the browser supplied filename, which in theory is the actual filename of the file.

Most likely the web browser user doesn't have access to `b/thumb`, i.e. the problem isn't the origin directory but rather the destination.

I'm closing this because it's not effecting all users, meaning it's a configuration problem on your end.

**Closed by ctrlcctrlv** 2019-04-18 12:33 UTC

**Comment by pfeifferj** [comment] 2019-04-18 13:12
Thanks for your reply. `/thumb` actually has the files uploaded in it, so permissions should be alright.
Anything else I might be missing?

**Comment by ctrlcctrlv** [comment] 2019-04-18 13:54
Not sure, really depends on how your web server is configured. Check permissions of target directory vis a vis the user your web server runs as. If it has write permissions but not execute it could cause this I think

**Comment by pfeifferj** [comment] 2019-04-18 14:49
Alright replacing `rename` with `copy` in `image.php` fixed it for me
