### ISSUE TITLE
My index show the directory

### ISSUE THREAD

**Issue by TheiNorbit** [vichan-devel/vichan#347] opened 2019-08-22 16:02 UTC
![20190822_043650](https://user-images.githubusercontent.com/54335981/63530300-2f77c500-c4d4-11e9-853c-6697c353f031.png)
How to have the final index, for the visitor to interact and make posts? I already did the whole installation. I'm using cPanel

**Comment by ctrlcctrlv** [comment] 2019-08-22 23:46
Duplicate of #346,user is spamming

**Closed by ctrlcctrlv** 2019-08-22 23:46 UTC
