### ISSUE TITLE
"X postsandY image repliesomitted" missing spaces in formatting on PHP 7.4

### ISSUE THREAD

**Issue by z0z0z** [vichan-devel/vichan#367] opened 2020-01-21 04:32 UTC
![2020-01-20-233513_379x56_scrot](https://user-images.githubusercontent.com/12925873/72775733-6e3ab400-3c07-11ea-83c7-e79b4a52ed20.png)

I tried figuring this one out myself.

This seems to be the original code that added this: https://github.com/vichan-devel/vichan/commit/55f082a4217cdc584dea6a59157d7cd725c7e329

And I found something related in `templates/post_thread.html`

**Comment by ctrlcctrlv** [comment] 2020-01-21 05:13
Basically you need to go through all the template files and add spaces where they don't exist around `{% if %}` blocks etc

**Comment by ctrlcctrlv** [comment] 2020-01-21 05:13
The problem is certainly related to #366

**Comment by z0z0z** [comment] 2020-01-21 05:24
```
	{% if post.omitted or post.omitted_images %}
		<span class="omitted">
			{% if post.omitted %}
				{% trans %}
					1 post
				{% plural post.omitted %}
					{{ count }} posts
				{% endtrans %}
				{% if post.omitted_images %}
					 {% trans %}and{% endtrans %} 
				{% endif %}
			{% endif %}
			{% if post.omitted_images %}
				{% trans %}
					1 image reply
				{% plural post.omitted_images %}
					{{ count }} image replies
				{% endtrans %}
			{% endif %} {% trans %}omitted. Click reply to view.{% endtrans %}
		</span>
	{% endif %}
```

So this is the template used for it.

Forgive my small brain, but adding whitespace after e.g."image replies", and then rebuilding everything in vichan, doesn't actually add whitespace.

Putting quotes around it like `"image replies "` does, but that cosmetically looks even worse tbh.

**Comment by ctrlcctrlv** [comment] 2020-01-21 05:27
You might need to delete the templates cache.

Try changing e.g. `{% trans %}omitted.` to `{% trans %} omitted.` etc.

**Comment by ctrlcctrlv** [comment] 2020-01-21 05:28
Oh or change the space after `{% endif %}` to `&nbsp;`

**Comment by z0z0z** [comment] 2020-01-21 05:29
Was also just trying the space before "and", "omitted", etc.

It just doesn't want to interpret it, changes are being made because if I change the words to "foobar" I see the change.

Will try &nbsp

**Comment by ctrlcctrlv** [comment] 2020-01-21 05:30
Yeah and I really have no !@#*)$ clue why this is happening but it's certainly a Twig issue.

ChAnGiNg ThE SpEc Is HaRmLeSs!!!

**Comment by z0z0z** [comment] 2020-01-21 05:32
```
			{% if post.omitted %}
				{% trans %}
					1 post
				{% plural post.omitted %}
					{{ count }} posts&nbsp;
				{% endtrans %}
				{% if post.omitted_images %}
					 {% trans %}and&nbsp;{% endtrans %} 
				{% endif %}
			{% endif %}
			{% if post.omitted_images %}
				{% trans %}
					1 image reply
				{% plural post.omitted_images %}
					{{ count }} image replies&nbsp;
				{% endtrans %}
			{% endif %} {% trans %}omitted. Click reply to view.{% endtrans %}
```

So this is what I have and it fixes, `&nbsp;` is respected.

I know this looks kinda ugly and I'm not sure if this is even used anywhere else, would you be okay a PR for this?

**Comment by ctrlcctrlv** [comment] 2020-01-21 05:39
OK. I will leave this open until I decide what to do. If you find these problems elsewhere please let us know.

**Comment by z0z0z** [comment] 2020-01-21 05:42
I've been testing almost everything, and I think aside from these two solved issues, I'm not seeing any problems with vichan on PHP 7.4.

There may be something internal complaining but everything is just working for me now.

**Comment by ctrlcctrlv** [comment] 2020-01-21 05:46
That's good. I opened a Twig issue but I think they might close it as it's a Twig 1.x issue and they're already on 3.x. Vichan's time is almost up I'm afraid, nu web developers don't give a shit about backwards compatibility or old software. Probably for many of them they were 8 years old in 2010. LOL

**Comment by ctrlcctrlv** [comment] 2020-01-21 11:22
@z0z0z Check this out https://github.com/twigphp/Twig/issues/3248#issuecomment-576635009 https://www.reddit.com/r/PHP/comments/ert97a/twig_1x_interprets_whitespace_differently_under/ff5q6bj/

**Comment by h00j** [comment] 2021-02-13 18:53
irrelevant since https://github.com/vichan-devel/vichan/pull/401, closing

**Closed by h00j** 2021-02-13 18:53 UTC
Labels: php7x-regression
