### ISSUE TITLE
undefined index: id error when deleting OP thread as user.

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#219] opened 2017-03-29 19:01 UTC
when you try to delete OP's thread you will get undefined index: id error and the post doesn't get deleted. if you try to delete it a second time it works. 

Does anyone experience the same bug and knows how to fix it? using vichan version 5.1.3.

**Comment by kekukin** [comment] 2017-03-29 21:15
I changed this code: on line 245 in the post.php file:

	`'/' . $board['dir'] . $config['dir']['res'] . link_for($post) . ($post['thread'] ? '#' . $id : '')`

to: 

	`'/' . $board['dir'] . $config['dir']['res'] . sprintf($config['file_page'], $post['thread'] ? $post['thread'] : $id) . ($post['thread'] ? '#' . $id : '')`

Need to see if it gives no other conflicts though.

**Comment by Taikuree** [comment] 2017-04-13 00:31
I'm getting this bug too. Your fix seems to work, can you confirm it doesn't conflict with anything?

**Comment by kekukin** [comment] 2017-04-13 13:31
Only redirects you to a 404 error when you delete a thread when you are inside a thread. Not a big deal for me. I plan on reverting the slugify modification... That's the change that gives the error. 
If you don't need slugify you can try my modification. I haven't reverted the slugify yet but will in the coming weeks. It's not stable though my modification of vichan. https://github.com/kekkin/H0K4CH4N

**Comment by Horija** [comment] 2017-04-24 08:01
```
-				'/' . $board['dir'] . $config['dir']['res'] . link_for($post) . ($post['thread'] ? '#' . $id : '')
 +				// link_for gives error when deleting a thread from the frontend. 
 +				// '/' . $board['dir'] . $config['dir']['res'] . link_for($post) . ($post['thread'] ? '#' . $id : '')
 +				'/' . $board['dir'] . $config['dir']['res'] . sprintf($config['file_page'], $post['thread'] ? $post['thread'] : $id) . ($post['thread'] ? '#' . $id : '')`
  			);
  		}
  	}

```
Just pasting this here cause might be related to this code in post.php

**Comment by ctrlcctrlv** [comment] 2017-11-05 13:30
Can't reproduce on my test instance - perhaps an issue with an upgrade. Closing due to ghosted user.

**Closed by ctrlcctrlv** 2017-11-05 13:30 UTC
