### ISSUE TITLE
make vichan work in php 8.0.2

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#397] opened 2021-02-09 13:35 UTC
As everyone is aware due to extensive media coverage, there is a growing international movement to make vichan work with php 8. How about an update on the status of that? Save vichan make it work with php 8+!!!!

**Comment by h00j** [comment] 2021-02-09 14:37
This is of course something that needs to be done, sooner or later. I can't tell you when it'll happen as of yet though.

**Comment by moon9snow** [comment] 2021-02-09 15:16
Cool, thanks!  No use wasting time on other fixes tho, because it might have to be fixed again when making vichan php 8 compatible. The great prophecy in the book of  Pepe says that  php 8 and on is the only way to go, as the end of life for the other versions will be here in the blink of an eye, much like a catastrophic flood in biblical times. Anyway, thanks for taking over  the prodject, Mr Hotwheels is cool but he is like... "heloooooo vichan is like 10 years old" and there is merit to his feelings on the matter, but the cult of Kek demands that vichan be used instead of the traditional bible, as it saves on trees that way. Looking forward to seeing what will become of Vichan. Thank you!

**Comment by z0z0z** [comment] 2021-02-13 14:30
For anyone who is wondering what happens when you run vichan on PHP 8

(TLDR: Nothing works)

If you try to load up /mod.php you get a blank page that just says 
```
Error
An error has occured.
Uninitialized string offset 0
```

If you try to make a text-only post as a user you get:

`Fatal error: Cannot declare class Twig_Autoloader, because the name is already in use in /var/www/inc/lib/Twig/Autoloader.php on line 21 Fatal error: Cannot declare class Twig_Autoloader, because the name is already in use in /var/www/inc/lib/Twig/Autoloader.php on line 21 `

If you try to make a post with a picture you get:

`Undefined array key "exif_stripped"`

**Comment by h00j** [comment] 2021-02-13 15:45
Cannot really reproduce this. Just tested vichan against php 8.0.0 and it looks functional.

**Comment by h00j** [comment] 2021-02-13 15:55
> `Fatal error: Cannot declare class Twig_Autoloader, because the name is already in use in /var/www/inc/lib/Twig/Autoloader.php on line 21 Fatal error: Cannot declare class Twig_Autoloader, because the name is already in use in /var/www/inc/lib/Twig/Autoloader.php on line 21`

This issue looks unrelated and will be fixed in #400

**Comment by moon9snow** [comment] 2021-02-13 19:51
I volunteer test installs- when its ready i can put vichan on ubuntu, fedora, debian or centos with php 8 + installed in order to have working demos. Also serverpilot.io is a great place to test because they have very decent security settings and use Apache to do php tasks in the background and also Nginx to serve static files and as a reverse proxy in order to improve security and speed. Also with serverpilot one can instantly change the php version form 7.4 to 8 which is great for testing, although ppl should just use pgp 8 and above to close the gap on outdated technology. Anyways, if anyone needs testing just let me know and i can spin up a server so there is live example demos of vichan and php8 compatibility issues. Also of note- while some may argue that other boards such as lynxchan are way more modern and way ahead of php, sometimes it is nice for people to deploy a vichan board because it is easy and quick to set up and quite reliable. Yes, more modern node js or golang boards are faster, but they rely on a huge amount of both dependencies and technical knowledge - and when something goes wrong it might be incredibly difficult to fix. There is merit to a simple php board that is admittedly slower, but it is reliable and easy to maintain and fix. Obviously 4chan is a good example that there is plenty of merit in php boards, even with the other alternative modern technology bundles that are out there. Vichan will  never be as fast or functional as node js boards, but if there was a focus on just making vichan reliable and easy to use, than vichan could still shine in it's own category, regardless of other technology out there.

**Comment by moon9snow** [comment] 2021-02-14 02:19
Here is what I got with an install attempt 


![vichan](https://user-images.githubusercontent.com/78183354/107866666-35d4cc00-6e41-11eb-88a0-c912dc08edb2.png)

**Comment by h00j** [comment] 2021-02-14 08:08
@moon9snow, please try the new version with composer. I've just merged it into the php8-compat branch.

**Comment by moon9snow** [comment] 2021-02-14 13:33
part 1 of 3 Here is composer-- output 
![composer](https://user-images.githubusercontent.com/78183354/107878260-56cc0a00-6e9f-11eb-9477-e8bb7d5a4e4b.png)

**Comment by moon9snow** [comment] 2021-02-14 13:34
![vichan0001](https://user-images.githubusercontent.com/78183354/107878266-60ee0880-6e9f-11eb-8557-647d91d92850.png)

here is all install.php shows when ran from browser

**Comment by moon9snow** [comment] 2021-02-14 13:45
Part 3 of 3

Lastly, when I chmod EVERYTHING to 777, install.php still only shows this. Sadly, i did a bit of research and most sources advise not even using twig at all- in fact they say it is absurd to use twig.


![instal0003](https://user-images.githubusercontent.com/78183354/107878435-b24ac780-6ea0-11eb-85c0-748c0c48c699.png)

**Comment by moon9snow** [comment] 2021-02-14 13:54
Oah and it was actually php 8.0.2 ---- not 8.0  you can see full server stats at https://4usa.org/vichan/z.php

**Comment by moon9snow** [comment] 2021-02-14 15:04
fyi i just made another test, ran composer from a non root account with proper permissions, exact same results

**Comment by adelia8** [comment] 2021-02-26 10:03
I haven't been able to get vichan even the php 8 branch working at all on php 8. It seems to  work  fine on 7.4 tho, all kinds of errors when i try to get it going on php 8.

**Comment by adelia8** [comment] 2021-03-04 18:00
Anyone have any luck getting vichan working on anything above php8.0  ????

**Comment by z0z0z** [comment] 2021-03-04 21:16
> Anyone have any luck getting vichan working on anything above php8.0 ????

Nope still gives me errors even with fully updated vichan

**Comment by adelia8** [comment] 2021-03-06 08:24
> > Anyone have any luck getting vichan working on anything above php8.0 ????
> 
> Nope still gives me errors even with fully updated vichan

AHHH OK, well others say it works, and i thought it was me being too dumb to install it :)  What a sad state of affairs. PHP  is supposed to be easy to work with. It seems easier to go back in time in order to use vichan than to get vichan working on latest php lol. 
Did anonib ruin the reputation of vichan so badly that no one wants anything to do with vichan any more? Did jschan and  lynx dev make vichan laughable to devs? Vichan has seen better days thats 4 sure. I am beginning to get the feeling that no one wants to push vichan dev to the latest php. Granted, ppl were saying vichan is too old to use like 7 years ago- ugh those ppl are only rigjt  if we let them be. Long live vichan, dammit.

**Comment by h00j** [comment] 2021-03-07 08:29
php8 compat isn't the highest priority on my list. It will be done and it is not hard to achieve, but I focus on other stuff at the moment. It's not that php 7.4 is eol or anything.

**Comment by ctrlcctrlv** [comment] 2022-08-29 15:49
Solved by #402 and https://github.com/vichan-devel/vichan/commit/572a11dba722cc7a7dbefc818a6a265535b3fcf1.

**Closed by ctrlcctrlv** 2022-08-29 15:49 UTC
Labels: more info needed
