### ISSUE TITLE
options.js / Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by Fabricio20** [vichan-devel/vichan#222] opened 2017-04-19 00:21 UTC
While doing script tests with vichan, I noticed the options.js script is failing to load up.

```
Uncaught TypeError: Cannot read property 'content' of undefined
    at Object.Options.extend_tab (options.js:76)
    at Object.add (inline.js:33)
    at HTMLDocument.<anonymous> (inline.js:126)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.I (jquery.min.js:2)
```

jQuery is set up and is the first script to be loaded.

**Comment by ctrlcctrlv** [comment] 2017-11-03 14:26
I'm not sure about this, but I think you need at least one of these scripts also, otherwise it gets confused because you're loading the options script but not requesting any options.

https://github.com/vichan-devel/vichan/tree/master/js/options

**Comment by ctrlcctrlv** [comment] 2017-11-05 13:45
I confirmed what I wrote above so am closing this.

**Closed by ctrlcctrlv** 2017-11-05 13:45 UTC
