### ISSUE TITLE
Page numbers not clickable on PHP 7.4

### ISSUE THREAD

**Issue by z0z0z** [vichan-devel/vichan#369] opened 2020-01-31 22:45 UTC
The page numbers aren't hyperlinks on PHP 7.4

![2020-01-31-174427_586x43_scrot](https://user-images.githubusercontent.com/12925873/73579786-5ec73080-447b-11ea-95e2-f07c5195c982.png)

This is probably pretty easy to fix though, do you know what files would be relevant to look at?

**Comment by ECHibiki** [comment] 2020-02-06 11:44
replace the ```<div class="pages">``` section of templates/index.html et al.
I added in spaces in particular locations, but the proper way to do it is inserting &nbsp; where required.
```
	<div class="pages">
		{{ btn.prev }} {% for page in pages %}
		 [<a class="{% if page.selected %} selected {% endif %}" {% if not page.selected %} href="{{ page.link }}"{% endif %}>{{ page.num }}</a>]{% if loop.last %} {% endif %}
		{% endfor %} {{ btn.next }}
		{% if config.catalog_link %}
			 | <a href="{{ config.root }}{{ board.dir }}{{ config.catalog_link }}">{% trans %}Catalog{% endtrans %}</a>
		{% endif %}
	</div>
```
https://github.com/ECHibiki/ViQa/blob/server/templates/index.php
My repo is non compatible with vichan(probably won't be since I'd rather rewrite the design in laravel MVC at this point) as it has components from NPFChan, integrations of software used bakape's Meguca, and my own reworking of the UI. The templates should work if you're careful about what you're doing.

**Comment by ctrlcctrlv** [comment] 2020-02-06 11:59
@ECHibiki Adding spaces, or `&nbsp;`, is a ridiculous solution and would not be accepted by us anyway. Please see #367 and https://github.com/twigphp/Twig/issues/3248#issuecomment-576635009 for the actual root cause of this problem.

**Comment by ECHibiki** [comment] 2020-02-06 12:03
"Basically you need to go through all the template files and add spaces where they don't exist around {% if %} blocks etc"

**Comment by ctrlcctrlv** [comment] 2020-02-06 12:08
Yes, that's a band-aid, but if PR'd, would be rejected.

**Comment by papereth** [comment] 2020-08-09 19:52
I have managed to remove the old version of Twig from my fork and install the latest 1.x Twig via PHP composer to make the problem go away.

If anyone is interested the steps I took are (more or less):
- Via composer require "twig/twig:^1.0" and "twig/extensions:^1.5".
- Move the `inc/lib/Twig/Extensions/Extension/Tinyboard.php` to `vendor/twig/extensions/lib/Twig/Extensions/Extension/Tinyboard.php`
- remove lines 14 to 28 (included) in `inc/template.php`
- add `require_once __DIR__ . '/../vendor/autoload.php';` on line 14 in `inc/template.php`
- nuke `inc/lib/Twig`

I think that's all I had to do, I'm reconstructing this from memory and commits to my private fork. I can try and do it on a fresh copy of vichan in a few weeks and open a PR for it if people are interested.

**Comment by z0z0z** [comment] 2020-08-09 22:47
I would be very interested and grateful in a PR.

I don't know how many vichan admins with active boards are still left but I'm still here and worry about future PHP compatibility mostly due to the old Twig version it seems.

**Comment by papereth** [comment] 2020-08-19 21:23
I still haven't found the time to test and PR what I've described above and I doubt I'll be able to do it until maybe mid September.
I'm fairly confident that the steps that I've highlighted above are all that's needed if anyone fancies giving it a go on a fresh install.

**Comment by ctrlcctrlv** [comment] 2020-08-20 00:11
No rush as far as I'm concerned. This project is essentially dormant. Thank you for your contributions, I'll review whatever you send, even if we end up breaking master for a few hours. 👍

**Comment by h00j** [comment] 2021-02-13 18:59
irrelevant since https://github.com/vichan-devel/vichan/pull/401, closing

**Closed by h00j** 2021-02-13 18:59 UTC
